In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('C:\\Users\\USER\\Documents\\e-com ML\\ecommerceDataset.csv ')
data.head()

Household  \
0  Household   
1  Household   
2  Household   
3  Household   
4  Household   

  Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  
0  SAF 'Floral' Framed Painting (Wood, 30 inch x ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
1  SAF 'UV Textured Modern Art Print Framed' Pain...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

In [3]:
data.tail()

Household  \
50419  Electronics   
50420  Electronics   
50421  Electronics   
50422  Electronics   
50423  Electronics   

      Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  
50419  Strontium MicroSD Class 10 8GB Memory Card (Bl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
50420  CrossBeats Wave Waterproof Bluetooth Wireless ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [4]:
import re
import string 

def preprocess_text(text):
    if not isinstance(text, str):text = str(text)
    #convert to lowercase
    text = text.lower()
    #remove punctuation marks and special character 
    text = text.translate(str.maketrans('','',string.punctuation))
    return text

data.columns = ['category','description']

data['cleaned_description'] = data['description'].apply(preprocess_text)

print("Original Data:")
print(data[['description']].head())
print("\nCleaned Data:")
print(data[['cleaned_description']].head())

Original Data:
                                         description
0  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1  SAF 'UV Textured Modern Art Print Framed' Pain...
2  SAF Flower Print Framed Painting (Synthetic, 1...
3  Incredible Gifts India Wooden Happy Birthday U...
4  Pitaara Box Romantic Venice Canvas Painting 6m...

Cleaned Data:
                                 cleaned_description
0  saf floral framed painting wood 30 inch x 10 i...
1  saf uv textured modern art print framed painti...
2  saf flower print framed painting synthetic 135...
3  incredible gifts india wooden happy birthday u...
4  pitaara box romantic venice canvas painting 6m...


In [10]:
import sklearn


from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(stop_words='english')

X = tfidf_vectorizer.fit_transform(data['cleaned_description'])
y = data['category']

print(f"Shape of TF-IDF matrix: {X.shape}")
print(f"Shape of target labels: {y.shape}")


Shape of TF-IDF matrix: (50424, 113085)
Shape of target labels: (50424,)


In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)

print("Data split complete.")
print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

Data split complete.
Training set shape: (40339, 113085)
Testing set shape: (10085, 113085)


In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
print("Training the model...")
model.fit(X_train, y_train)

print("model training complete")

Training the model...
model training complete


In [14]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

y_pred = model.predict(X_test)

print("\n--- Model performance Evaluation---")
print(f"Accuracy:{accuracy_score(y_test,y_pred):.4f}")

print("\nClassification Report:")
print(classification_report(y_test,y_pred))

print("\nConfusion matrix:")
print(confusion_matrix(y_test,y_pred))


--- Model performance Evaluation---
Accuracy:0.9657

Classification Report:
                        precision    recall  f1-score   support

                 Books       0.97      0.96      0.96      2364
Clothing & Accessories       0.98      0.97      0.98      1734
           Electronics       0.97      0.95      0.96      2124
             Household       0.95      0.98      0.97      3863

              accuracy                           0.97     10085
             macro avg       0.97      0.96      0.97     10085
          weighted avg       0.97      0.97      0.97     10085


Confusion matrix:
[[2262   15   18   69]
 [  10 1681    8   35]
 [  36    2 2008   78]
 [  27   13   35 3788]]
